"""change-vertex_id-field-type-to-string

Revision ID: 15465cf380bc
Revises: 99cf591b745a
Create Date: 2026-06-07 02:48:20.282544

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15465cf380bc"
down_revision: str | None = "99cf591b745a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("span", schema=None) as batch_op:
        batch_op.alter_column(
            "vertex_id",
            existing_type=sa.CHAR(length=32),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("span", schema=None) as batch_op:
        batch_op.alter_column(
            "vertex_id",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.CHAR(length=32),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
