"""refactor-tables

Revision ID: 2370e4eba486
Revises: 6fd1730b4098
Create Date: 2026-05-20 21:31:12.630365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2370e4eba486'
down_revision: Union[str, None] = '6fd1730b4098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_metric',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('algorithm', sa.Enum('AGENT_AS_JUDGE', 'TOOL_EVALUATION', 'RAG_EVALUATION', name='evaluation_algorithm_enum'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_case',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_output', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['eval_metric.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('eval_case_id', sa.Uuid(), nullable=False),
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('result_explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['eval_case_id'], ['eval_case.id'], ),
    sa.ForeignKeyConstraint(['trace_id'], ['trace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('evaluationresultexperimental')
    op.drop_table('evaluationexperimental')
    op.drop_table('evaluationresult')
    op.drop_table('evaluationcase')
    op.drop_table('evaluationmetric')
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluationmetric',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('algorithm', sa.VARCHAR(length=15), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluationmetric'))
    )
    op.create_table('evaluationcase',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('flow_id', sa.CHAR(length=32), nullable=False),
    sa.Column('metric_id', sa.CHAR(length=32), nullable=False),
    sa.Column('input', sa.VARCHAR(), nullable=False),
    sa.Column('expected_output', sa.VARCHAR(), nullable=False),
    sa.Column('min_iterations', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], name=op.f('fk_evaluationcase_flow_id_flow')),
    sa.ForeignKeyConstraint(['metric_id'], ['evaluationmetric.id'], name=op.f('fk_evaluationcase_metric_id_evaluationmetric')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluationcase'))
    )
    op.create_table('evaluationresult',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('evaluation_case_id', sa.CHAR(length=32), nullable=False),
    sa.Column('input_tokens', sa.INTEGER(), nullable=False),
    sa.Column('output_tokens', sa.INTEGER(), nullable=False),
    sa.Column('actual_output', sa.VARCHAR(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('time', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_case_id'], ['evaluationcase.id'], name=op.f('fk_evaluationresult_evaluation_case_id_evaluationcase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluationresult'))
    )
    op.create_table('evaluationexperimental',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('input', sa.VARCHAR(), nullable=False),
    sa.Column('expected_output', sa.VARCHAR(), nullable=False),
    sa.Column('prompt', sa.VARCHAR(), nullable=False),
    sa.Column('model_name', sa.VARCHAR(), nullable=False),
    sa.Column('flow_id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], name=op.f('fk_evaluationexperimental_flow_id_flow')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_evaluationexperimental_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluationexperimental'))
    )
    op.create_table('evaluationresultexperimental',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('actual_output', sa.VARCHAR(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('eval_message', sa.VARCHAR(), nullable=False),
    sa.Column('success', sa.BOOLEAN(), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('evaluation_case_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_case_id'], ['evaluationexperimental.id'], name=op.f('fk_evaluationresultexperimental_evaluation_case_id_evaluationexperimental')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_evaluationresultexperimental_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluationresultexperimental'))
    )
    op.drop_table('eval_run')
    op.drop_table('eval_case')
    op.drop_table('eval_metric')
    # ### end Alembic commands ###
