"""

Revision ID: 6fd1730b4098
Revises: a17575c821a7
Create Date: 2026-05-20 00:46:21.418968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '6fd1730b4098'
down_revision: Union[str, None] = 'a17575c821a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluationmetric', schema=None) as batch_op:
        batch_op.alter_column('algorithm',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('AGENT_AS_JUDGE', 'TOOL_EVALUATION', 'RAG_EVALUATION', name='evaluation_algorithm_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluationmetric', schema=None) as batch_op:
        batch_op.alter_column('algorithm',
               existing_type=sa.Enum('AGENT_AS_JUDGE', 'TOOL_EVALUATION', 'RAG_EVALUATION', name='evaluation_algorithm_enum'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###
