"""revision-26-05-2026

Revision ID: 72cd64ae2a18
Revises: eeffb5135c21
Create Date: 2026-05-26 23:48:44.975518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '72cd64ae2a18'
down_revision: Union[str, None] = 'eeffb5135c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eval_case', schema=None) as batch_op:
        batch_op.alter_column('input',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               nullable=True)

    with op.batch_alter_table('eval_metric', schema=None) as batch_op:
        batch_op.alter_column('algorithm',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('AGENT_AS_A_JUDGE', 'TOOL_EVALUATION', 'RAG_EVALUATION', name='evaluation_algorithm_enum'),
               existing_nullable=False)

    with op.batch_alter_table('eval_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('err_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('result_explanation')
        batch_op.drop_column('duration')
        batch_op.drop_column('status')
        batch_op.drop_column('output_tokens')
        batch_op.drop_column('input_tokens')

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eval_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_tokens', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('output_tokens', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('result_explanation', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('err_message')
        batch_op.drop_column('message')

    with op.batch_alter_table('eval_metric', schema=None) as batch_op:
        batch_op.alter_column('algorithm',
               existing_type=sa.Enum('AGENT_AS_A_JUDGE', 'TOOL_EVALUATION', 'RAG_EVALUATION', name='evaluation_algorithm_enum'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    with op.batch_alter_table('eval_case', schema=None) as batch_op:
        batch_op.alter_column('input',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
