"""change-evalcase-input-type-to-dict

Revision ID: 905543d0fd7b
Revises: 6b5cbc0eebb7
Create Date: 2026-05-31 23:21:09.373769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '905543d0fd7b'
down_revision: Union[str, None] = '6b5cbc0eebb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
