"""add-vertex_id-field-to-span-table

Revision ID: 99cf591b745a
Revises: 96e2d082fd1d
Create Date: 2026-06-05 00:49:57.080944

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99cf591b745a"
down_revision: str | None = "96e2d082fd1d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("span", schema=None) as batch_op:
        batch_op.add_column(sa.Column("vertex_id", sa.Uuid(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("span", schema=None) as batch_op:
        batch_op.drop_column("vertex_id")

    # ### end Alembic commands ###
