"""evaluations

Revision ID: abf79eeeb87d
Revises: d306e5c17c41
Create Date: 2026-05-04 23:46:41.184646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = 'abf79eeeb87d'
down_revision: Union[str, None] = 'd306e5c17c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluationmetric',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('algorithm', sa.Enum('AGENT_AS_JUDGE', name='evaluation_algorithm_enum'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluationcase',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('input', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_output', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_iterations', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['evaluationmetric.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluationresult',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_case_id', sa.Uuid(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('actual_output', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_case_id'], ['evaluationcase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluationresult')
    op.drop_table('evaluationcase')
    op.drop_table('evaluationmetric')
    # ### end Alembic commands ###
