"""add-metrics-field-to-evalcase

Revision ID: eeffb5135c21
Revises: 2648b24abbda
Create Date: 2026-05-26 20:36:30.696785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = 'eeffb5135c21'
down_revision: Union[str, None] = '2648b24abbda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casemetriclink',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['eval_case.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['eval_metric.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'metric_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casemetriclink')
    # ### end Alembic commands ###
