"""change-08-06-2026

Revision ID: f9a225fe7f36
Revises: b7a4d1e2c3f4
Create Date: 2026-06-08 10:24:58.911867

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9a225fe7f36"
down_revision: str | None = "b7a4d1e2c3f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eval_batch",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("flow_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "trigger_mode",
            sa.Enum("single_case", "selected_cases", "all_cases", "legacy", name="eval_batch_trigger_mode_enum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "completed_with_errors",
                "failed",
                "cancelled",
                name="eval_batch_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("requested_case_count", sa.Integer(), nullable=False),
        sa.Column("completed_case_count", sa.Integer(), nullable=False),
        sa.Column("failed_case_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["flow_id"], ["flow.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("eval_batch", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eval_batch_flow_id"), ["flow_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_eval_batch_user_id"), ["user_id"], unique=False)

    op.create_table(
        "eval_case_execution",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("eval_batch_id", sa.Uuid(), nullable=False),
        sa.Column("eval_case_id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=True),
        sa.Column("flow_session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "completed_with_errors",
                "failed",
                name="eval_case_execution_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("case_snapshot", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["eval_batch_id"], ["eval_batch.id"]),
        sa.ForeignKeyConstraint(["eval_case_id"], ["eval_case.id"]),
        sa.ForeignKeyConstraint(["trace_id"], ["trace.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("eval_case_execution", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eval_case_execution_eval_batch_id"), ["eval_batch_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_eval_case_execution_eval_case_id"), ["eval_case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_eval_case_execution_flow_session_id"), ["flow_session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_eval_case_execution_trace_id"), ["trace_id"], unique=False)

    with op.batch_alter_table("eval_run", schema=None) as batch_op:
        batch_op.add_column(sa.Column("eval_case_execution_id", sa.Uuid(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_eval_run_eval_case_execution_id"), ["eval_case_execution_id"], unique=False
        )
        batch_op.create_foreign_key(None, "eval_case_execution", ["eval_case_execution_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("eval_run", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_eval_run_eval_case_execution_id"))
        batch_op.drop_column("eval_case_execution_id")

    with op.batch_alter_table("eval_case_execution", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_case_execution_trace_id"))
        batch_op.drop_index(batch_op.f("ix_eval_case_execution_flow_session_id"))
        batch_op.drop_index(batch_op.f("ix_eval_case_execution_eval_case_id"))
        batch_op.drop_index(batch_op.f("ix_eval_case_execution_eval_batch_id"))

    op.drop_table("eval_case_execution")
    with op.batch_alter_table("eval_batch", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_batch_user_id"))
        batch_op.drop_index(batch_op.f("ix_eval_batch_flow_id"))

    op.drop_table("eval_batch")
    # ### end Alembic commands ###
